apiVersion: apps/v1
kind: Deployment
metadata:
  name: dippy-bot
  labels:
    app: dippy-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beginner-py-bot
  template:
    metadata:
      labels:
        app: beginner-py-bot
    spec:
      containers:
        - name: dippy-bot
          image: zzmmrmn/dippy-bot:<IMAGE_VERSION>
          envFrom:
            - configMapRef:
                name: dippy-bot-config
            - secretRef:
                name: discord-bot-secrets
          env:
            - name: PRODUCTION_BOT
              value: "PRODUCTION"
            - name: "DISCORD_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: discord.token
                  key: token
            - name: "BOT_IMAGE_VERSION"
              value: "<IMAGE_VERSION>"
