on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building & Deploying Beginner.py Bot (Dippy)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dippy-rewrite
      uses: actions/checkout@master

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

    - name: Build container image
      run: docker build -t zzmmrmn/bpy-dippy-bot:$(echo $GITHUB_SHA | head -c7) .

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push image to Docker Hub
      run: docker push zzmmrmn/bpy-dippy-bot:$(echo $GITHUB_SHA | head -c7)
    - name: Update deployment file
      run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|<IMAGE_VERSION>|'${TAG}'|' $GITHUB_WORKSPACE/manifests/bot.yaml

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save personal-kubernetes

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/manifests/bot.yaml -n bpy

    - name: Verify deployment
      run: kubectl rollout status deployment/bpy-dippy-bot -n bpy
